
import logging

DEFAULT_EMBEDDING_DIM = 768
DEFAULT_ST_MODEL = "LaBSE"
DEFAULT_LOGGING_LEVEL = logging.INFO
DEFAULT_LOGGING_FORMAT = "[%(asctime)s] [%(levelname)s] [%(module)s:%(lineno)d] %(message)s"
DEFAULT_MAX_MBYTES_PER_BATCH = 500
DEFAULT_BATCH_SIZE = 32
DEFAULT_SENTENCE_SPLITTING = False

ST_SHOW_PROGRESS = False
